### ISSUE TITLE
putting chai in the test chunk causes tests to throw

### ISSUE THREAD

**Issue by ssube** [ssube/salty-dog#16]
Adding chai to the `test` chunk via `manualChunks` (`id.includes('/chai/')`) causes the test run to throw an error:

```
created out/ in 5s
/home/ssube/code/ssube/salty-dog//node_modules/.bin/mocha /home/ssube/code/ssube/salty-dog//out/test.js
/home/ssube/code/ssube/salty-dog/node_modules/mocha/node_modules/yargs/yargs.js:1163
      else throw err
           ^

TypeError: __chunk_1.createCommonjsModule is not a function
    at Object.<anonymous> (/home/ssube/code/ssube/salty-dog/out/vendor.js:3899:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/ssube/code/ssube/salty-dog/out/test.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at /home/ssube/code/ssube/salty-dog/node_modules/mocha/lib/mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/ssube/code/ssube/salty-dog/node_modules/mocha/lib/mocha.js:327:14)
    at Mocha.run (/home/ssube/code/ssube/salty-dog/node_modules/mocha/lib/mocha.js:804:10)
    at Object.exports.singleRun (/home/ssube/code/ssube/salty-dog/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/home/ssube/code/ssube/salty-dog/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (/home/ssube/code/ssube/salty-dog/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/home/ssube/code/ssube/salty-dog/node_modules/mocha/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/ssube/code/ssube/salty-dog/node_modules/mocha/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/home/ssube/code/ssube/salty-dog/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/home/ssube/code/ssube/salty-dog/node_modules/mocha/lib/cli/cli.js:63:6)
    at Object.<anonymous> (/home/ssube/code/ssube/salty-dog/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
Makefile:83: recipe for target 'test' failed
make: *** [test] Error 1
```

Fix that and get test deps out of the `vendor` chunk.

**Comment by ssube** [comment]
This may be related to synthetic imports, but has been fixed in noicejs - copy that.

**Comment by ssube** [comment]
This is due to circular imports within chai, afaict, and was resolved by external-ing it.
